name: Publish to Chrome Web Store
description: Upload and publish extension to Chrome Web Store using curl

inputs:
  chrome-client-id:
    description: Chrome OAuth Client ID
    required: true
  chrome-client-secret:
    description: Chrome OAuth Client Secret
    required: true
  chrome-refresh-token:
    description: Chrome OAuth Refresh Token
    required: true
  chrome-extension-id:
    description: Chrome Web Store Extension ID
    required: true
  zip-file:
    description: Path to the zip file to upload
    required: true
  publish:
    description: Whether to publish after upload (true/false)
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Validate zip file
      run: |
        if [ ! -f "${{ inputs.zip-file }}" ]; then
          echo "❌ Zip file not found: ${{ inputs.zip-file }}"
          exit 1
        fi
        echo "✅ Zip file found: $(ls -lh ${{ inputs.zip-file }})"
      shell: bash

    - name: Get Chrome Web Store access token
      id: auth
      run: |
        ACCESS_TOKEN=$(curl -s \
          -X POST \
          -d "client_id=${{ inputs.chrome-client-id }}" \
          -d "client_secret=${{ inputs.chrome-client-secret }}" \
          -d "refresh_token=${{ inputs.chrome-refresh-token }}" \
          -d "grant_type=refresh_token" \
          https://oauth2.googleapis.com/token | jq -r '.access_token')

        if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" = "null" ]; then
          echo "❌ Failed to get access token"
          exit 1
        fi

        echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
        echo "✅ Got Chrome Web Store access token"
      shell: bash

    - name: Upload to Chrome Web Store
      run: |
        RESPONSE=$(curl -s -X PUT \
          -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
          -H "x-goog-api-version: 2" \
          -H "Content-Type: application/zip" \
          --data-binary @"${{ inputs.zip-file }}" \
          https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ inputs.chrome-extension-id }})

        echo "Response: $RESPONSE"

        # Check for errors
        ERROR=$(echo "$RESPONSE" | jq -r '.error.message // empty')
        if [ ! -z "$ERROR" ]; then
          echo "❌ Upload failed: $ERROR"
          exit 1
        fi

        echo "✅ Successfully uploaded to Chrome Web Store"
      shell: bash

    - name: Publish to Chrome Web Store
      if: inputs.publish == 'true'
      run: |
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
          -H "x-goog-api-version: 2" \
          -H "Content-Type: application/json" \
          -d '{"target":"default"}' \
          https://www.googleapis.com/chromewebstore/v1.1/items/${{ inputs.chrome-extension-id }}/publish)

        echo "Response: $RESPONSE"

        STATUS=$(echo "$RESPONSE" | jq -r '.status // empty')
        if [ "$STATUS" = "IN_PROGRESS" ] || [ "$STATUS" = "PUBLISHED" ]; then
          echo "✅ Extension published to Chrome Web Store"
        elif [ -z "$STATUS" ]; then
          ERROR=$(echo "$RESPONSE" | jq -r '.error.message // empty')
          if [ ! -z "$ERROR" ]; then
            echo "⚠️  Publish failed: $ERROR (extension may still be in review)"
          fi
        fi
      shell: bash
      continue-on-error: true
