name: Publish to Firefox
description: Sign and publish extension to Firefox Add-ons (AMO)

inputs:
  firefox-api-key:
    description: Firefox API key from AMO
    required: true
  firefox-api-secret:
    description: Firefox API secret from AMO
    required: true

outputs:
  xpi-file:
    description: Path to the signed XPI file (if successful)
    value: ${{ steps.sign.outputs.xpi-file || 'none' }}

runs:
  using: composite
  steps:
    - name: Install web-ext
      run: npm install -g web-ext
      shell: bash

    - name: Sign extension for Firefox
      id: sign
      run: |
        web-ext sign \
          --api-key="${{ inputs.firefox-api-key }}" \
          --api-secret="${{ inputs.firefox-api-secret }}" \
          --source-dir=dist \
          --artifacts-dir=./artifacts

        # Find the XPI file
        XPI_FILE=$(find ./artifacts -name "*.xpi" -type f | head -1)
        if [ -f "$XPI_FILE" ]; then
          echo "xpi-file=$XPI_FILE" >> $GITHUB_OUTPUT
          echo "✅ XPI file created: $XPI_FILE"
        else
          echo "❌ No XPI file found"
          exit 1
        fi
      shell: bash
      continue-on-error: true

    - name: Upload XPI to GitHub release
      if: steps.sign.outputs.xpi-file != 'none'
      run: |
        gh release upload ${{ github.event.release.tag_name }} ${{ steps.sign.outputs.xpi-file }}
      shell: bash
      continue-on-error: true
